export const getCustomers = () => [
  {
    name: "Hart Hagerty",
    img: "2",
    location: "United States",
    company: "Zemlak, Daniel and Leannon",
    job: "Desktop Support Technician",
    color: "Purple",
  },
  {
    name: "Brice Swyre",
    img: "3",
    location: "China",
    company: "Carroll Group",
    job: "Tax Accountant",
    color: "Red",
  },
  {
    name: "Marjy Ferencz",
    img: "4",
    location: "Russia",
    company: "Rowe-Schoen",
    job: "Office Assistant I",
    color: "Crimson",
  },
  {
    name: "Yancy Tear",
    img: "5",
    location: "Brazil",
    company: "Wyman-Ledner",
    job: "Community Outreach Specialist",
    color: "Indigo",
  },
  {
    name: "Hart Hagerty",
    img: "2",
    location: "United States",
    company: "Zemlak, Daniel and Leannon",
    job: "Desktop Support Technician",
    color: "Purple",
  },
  {
    name: "Brice Swyre",
    img: "3",
    location: "China",
    company: "Carroll Group",
    job: "Tax Accountant",
    color: "Red",
  },
  {
    name: "Marjy Ferencz",
    img: "4",
    location: "Russia",
    company: "Rowe-Schoen",
    job: "Office Assistant I",
    color: "Crimson",
  },
  {
    name: "Yancy Tear",
    img: "5",
    location: "Brazil",
    company: "Wyman-Ledner",
    job: "Community Outreach Specialist",
    color: "Indigo",
  },
  {
    name: "Hart Hagerty",
    img: "2",
    location: "United States",
    company: "Zemlak, Daniel and Leannon",
    job: "Desktop Support Technician",
    color: "Purple",
  },
  {
    name: "Brice Swyre",
    img: "3",
    location: "China",
    company: "Carroll Group",
    job: "Tax Accountant",
    color: "Red",
  },
  {
    name: "Marjy Ferencz",
    img: "4",
    location: "Russia",
    company: "Rowe-Schoen",
    job: "Office Assistant I",
    color: "Crimson",
  },
  {
    name: "Yancy Tear",
    img: "5",
    location: "Brazil",
    company: "Wyman-Ledner",
    job: "Community Outreach Specialist",
    color: "Indigo",
  },
  {
    name: "Hart Hagerty",
    img: "2",
    location: "United States",
    company: "Zemlak, Daniel and Leannon",
    job: "Desktop Support Technician",
    color: "Purple",
  },
  {
    name: "Brice Swyre",
    img: "3",
    location: "China",
    company: "Carroll Group",
    job: "Tax Accountant",
    color: "Red",
  },
  {
    name: "Marjy Ferencz",
    img: "4",
    location: "Russia",
    company: "Rowe-Schoen",
    job: "Office Assistant I",
    color: "Crimson",
  },
  {
    name: "Yancy Tear",
    img: "5",
    location: "Brazil",
    company: "Wyman-Ledner",
    job: "Community Outreach Specialist",
    color: "Indigo",
  },
];
